### ISSUE TITLE
gbc-census: Add my device

### ISSUE THREAD

**Issue by 3615Retro** [ace-dent/gbc-hw#3]
![image](https://github.com/user-attachments/assets/a45c633c-7112-4fe4-8126-0c21b289bfa0)

Serial :
CH20409368
CPU :
05
bought on :
Second hand market french website

**Comment by ace-dent** [comment]
Perfect! Thanks. May I attribute the source to your GitHub handle `@3615Retro` ?

**Comment by 3615Retro** [comment]
Should I add a line to differentiate CPU and board ID ? Such as
CPU : D
Board : CGB-CPU-05

Yep GitHub handle is perfect :)

**Comment by ace-dent** [comment]
The photo contains everything I need. I don't record the CPU revision, as it's not normally visible. 
You may also want to contact @gekkio to see if you can submit to their [database](https://github.com/Gekkio/gb-hardware-db). Many thanks again.

**Comment by ace-dent** [comment]
@3615Retro - not sure if you still have this device(?), but it would actually be useful to grab a photo of the reverse side of the PCB. I have started a sub-project to capture some extra device details.

**Comment by 3615Retro** [comment]
I don't unfortunately :(

**Comment by ace-dent** [comment]
> I don't unfortunately :(

Ok. No worries :-)
